name: Recent Activity

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g @actions/core @actions/github
      - uses: teoxoy/profile-readme-stats@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
